### ISSUE TITLE
Local Cache Feature 

### ISSUE THREAD

**Issue by afnx** [algolia/algoliasearch-helper-flutter#106]
Hello, I'm new to Algolia and I'm curious if it has a feature that stores data on the device locally to improve the performance. I couldn't find any information on caching in the documentation. 

Does this package always request data from the server every time for the same query?

**Comment by VladislavFitz** [comment]
Hi @afnx ,
Thank you for your inquiry. As of now, our library does not include built-in caching functionality. We appreciate your suggestion and have noted it for consideration in potential future enhancements. However, we cannot guarantee its implementation in the near term. Your feedback is valuable, and we'll certainly keep it in mind as we continue to evolve our library.

**Comment by toshiossada** [comment]
any update about this?
