### ISSUE TITLE
FacetList.eventTracker.clickedFilters throws 422 syntax error

### ISSUE THREAD

**Issue by sparkmagicllc** [algolia/algoliasearch-helper-flutter#108]
**Describe the bug 🐛**  
Insights Events API request payload body has a syntax error
AlgoliaApiException{statusCode: 422, error:
{"status":422,"message":"Syntax error near: `\"Facet Value\"`, expected a filter"}}:

**To Reproduce 🔍**  

1. click Facet List and toggle selection of a facet filter value
2. eventTracker is enabled

**Expected behavior 💭**  
```
FacetList.eventTracker.clickedFilters(
        eventName: 'testing clicked filter',
        values: ["facet_name:"+Uri.encodeComponent(facet_value)]);

```
**Screenshots 🖥**  

**Environment:**
- all
**Additional context**

**Comment by Peetee06** [comment]
I just ran into the same issue following the `Getting started` guide using our own Algolia application. The filters seem to be correctly applied nevertheless.
