### ISSUE TITLE
Support algolia version 1.0.0

### ISSUE THREAD

**Issue by Wackymax** [algolia/algoliasearch-helper-flutter#111]
**Is your feature request related to a problem? Please describe 🙏**  
The Algolia library recently moved to stable version 1.0.0.

**Describe the solution you'd like 🤔**  
Can this lib be updated to support the latest version of the Algolia dart SDK?

**Describe alternatives you've considered ✨**  
N/A

**Additional context**  
N/A

**Comment by VladislavFitz** [comment]
Hi @Wackymax ,

Thank you for the suggestion. We're currently working on updating our library to support the latest Algolia Dart SDK version 1.0.0. We'll keep you posted on the progress.

**Comment by Wackymax** [comment]
Thank you @VladislavFitz I see the changes were updated but you did not update the version for this lib and push a new release?
