### ISSUE TITLE
'demo_ecommerce' data search error: Method not allowed with this API key

### ISSUE THREAD

**Issue by Patrick386** [algolia/algoliasearch-helper-flutter#113]
**Algolia demo data:**
To read Algolia 'demo_ecommerce,' which key should I use? I've tried both the admin key and the search key, but I couldn't read the data.
Thank you.

```
  HitsSearcher hitsSearcher = HitsSearcher(
    applicationID: Env.algoliaApplicationID,
    apiKey: Env.algoliaAdminKey, // adminKey 
    indexName: AlgoliaCredentials.demoEcommerceIndex, // demo_ecommerce
  );
```

![image](https://github.com/algolia/algoliasearch-helper-flutter/assets/49754877/957c774a-d0df-41a0-ad37-e67880f2c055)

![image](https://github.com/algolia/algoliasearch-helper-flutter/assets/49754877/446934bf-aa22-4753-a97d-312c84225f86)

search key: demo_ecommerce
![image](https://github.com/algolia/algoliasearch-helper-flutter/assets/49754877/92eca431-695b-47ec-ba2f-d82c81f0a5a3)

**Comment by VladislavFitz** [comment]
Hi @Patrick386,

To access the 'demo_ecommerce' index, you should typically use the search-only API key, as it is sufficient for performing searches within the index. However, since you mentioned encountering issues, could you please provide more details about the specific error or problem you're facing?

**Comment by Patrick386** [comment]
> Hi @Patrick386,
> 
> To access the 'demo_ecommerce' index, you should typically use the search-only API key, as it is sufficient for performing searches within the index. However, since you mentioned encountering issues, could you please provide more details about the specific error or problem you're facing?

Yes, that's correct. The search-only API key was sufficient. The issue was an error caused by a field in the model that didn't match the expected type. Thank you.
