### ISSUE TITLE
Expose Timeout Duration

### ISSUE THREAD

**Issue by ebsangam** [algolia/algoliasearch-helper-flutter#138]
**Describe the bug 🐛**  
When using HitSearcher we often get timeout since default timeout is only 2 seconds. We may need the ability to override the default timeout duration.

**To Reproduce 🔍**  

**Expected behavior 💭**  

**Screenshots 🖥**  

**Environment:**

- OS: [e.g. iOS, android, web]
- Library Version [e.g. 1.1.0]

**Additional context**

**Comment by dhayab** [comment]
Hi, we just published algolia_helper_flutter v1.1.0, which lets you [customize client options from HitsSearcher](https://pub.dev/documentation/algolia_helper_flutter/latest/algolia_helper_flutter/HitsSearcher/HitsSearcher.html).
