### ISSUE TITLE
Personalization? 

### ISSUE THREAD

**Issue by Patrick386** [algolia/algoliasearch-helper-flutter#39]
I do not want to import data registered by other users.
What settings do I need for personalization?

```
 final HitsSearcher _addressBookSearcher = HitsSearcher.create(
      applicationID: AlgoliaCredentials.applicationID,
      apiKey: AlgoliaCredentials.apiKey,
      state:  const SearchState(
          indexName: AlgoliaCredentials.addressBookIndex,
          query: '',
         userToken: <<<<<<<< ?
      ));
```
I passed userToken but it doesn't work.

**Comment by Aallam** [comment]
Hi @Patrick386, can you please clarify what you mean by "_import data registered by other users_"?
Could you please explain or give an example of the behavior you are trying to achieve?

**Comment by Aallam** [comment]
Hi again! Yes, it's possible, and it corresponds to [personalized catalogs](https://www.algolia.com/doc/guides/solutions/ecommerce/b2b-catalog-management/tutorials/personalized-catalogs/). 
As mentioned [here](https://www.algolia.com/doc/guides/solutions/ecommerce/b2b-catalog-management/tutorials/personalized-catalogs/#accessing-personalized-product-catalogs-with-secured-api-keys), you will need the following steps: 
1. When users start searching, your _Flutter app_ requests a secured API key from your server. Your server creates a secured API key with a pre-applied filter and returns it to your Flutter app.
2. Your Flutter app uses the secured API key for searching with your `HitsSearcher` (as `apiKey`)

**Comment by Patrick386** [comment]
> 

I executed it according to your explanation and the results are as follows.
First, the secured API key was generated and delivered to the user using Cloud function.
I made sure that only my data was retrieved, and it worked very well.
Thank you.

*Question
I want to see the revised list immediately once I modify the item on the product list page. How can I make it work?

**Comment by Aallam** [comment]
Hi, can you please explain more in detail the workflow? what do you mean by "modify the item on the product list page"?

**Comment by Patrick386** [comment]
> Hi, can you please explain more in detail the workflow? what do you mean by "modify the item on the product list page"?

Hi, The question is not related to this package, I solved the problem.
The package works very well. thank you
