### ISSUE TITLE
Category page

### ISSUE THREAD

**Issue by Patrick386** [algolia/algoliasearch-helper-flutter#41]
I am looking for a way to manage product categories efficiently. 
For example, I want to change the category name.
Which of the two solutions below does Algolia recommend?

For Solution A, all records must be modified to rename the category. Is it right?

For Solution B, it requires join, and I want to know if it provides this function.

<img width="1331" alt="스크린샷 2022-10-29 오후 8 38 15" src="https://user-images.githubusercontent.com/49754877/198830733-ebc14b07-fe99-454f-b656-3b3431a8c442.png">

**Comment by Aallam** [comment]
Hi @Patrick386, the best would be to update your hits and reindex them, which corresponds to your Solution A. This may come in handy for other features later on (e.g. search for facet values).

**Comment by Patrick386** [comment]
> Hi @Patrick386, the best would be to update your hits and reindex them, which corresponds to your Solution A. This may come in handy for other features later on (e.g. search for facet values).

Hi, You're right.  SolutionB did not fit into No-SQL and was more complex. 
Thank you.
