### ISSUE TITLE
Unsafe header Issue with HitsSearcher

### ISSUE THREAD

**Issue by ranvirsahota** [algolia/algoliasearch-helper-flutter#55]
**Describe the bug 🐛**  
Every time I execute a search I get an error in the chrome dev console. Only on chrome, nothing noted on Firefox. The code I use to execute a search is below. 
**To Reproduce 🔍**  
The first time the page loads I this runs, I am also using the bloc architecture. I get this issue whether I use HitsSearcher then use applyState or the factory method like below.
```dart
      final _searcher = HitsSearcher.create(
        applicationID: ALGOLIA_APPLICATION_ID,
        apiKey: ALGOLIA_INVOICES_INDEX_KEY,
        state: SearchState(
          indexName: ALGOLIA_INVOICES_INDEX_NAME,
          page: page,
          hitsPerPage: 10,
        ),
      );
```
Deploy it to Chrome

**Expected behavior 💭**  
In the web browser Console
```
Refused to set unsafe header "User-Agent"
```

**Screenshots 🖥**  

**Environment:**

- OS: [5.15.78-1-MANJARO]
- Browser: [Chrome Chrome Version 108.0.5359.71 (Official Build) (64-bit)]
- Library Version [algolia_helper_flutter: ^0.2.1]

**Additional context**

**Comment by VladislavFitz** [comment]
Beginning with version [0.4.0](https://github.com/algolia/algoliasearch-helper-flutter/releases/tag/algolia_helper_flutter-v0.4.0), our library has integrated the [official Dart API client](https://github.com/algolia/algoliasearch-client-dart), which employs the `x-algolia-agent`. This update has resolved the issue in question.
