### ISSUE TITLE
MultiSearchers

### ISSUE THREAD

**Issue by dretoba91** [algolia/algoliasearch-helper-flutter#60]
**Is your feature request related to a problem? Please describe 🙏**  
I'm trying to query two indexes, with requires MultiSearcher method.

**Describe the solution you'd like 🤔**  
A need for the MultiSearcher method since HitsSearcher method doesn't handle multiple indexes.

**Describe alternatives you've considered ✨**  
I've tried different ways, but none works.

**Additional context**  
![image](https://user-images.githubusercontent.com/64743870/222207177-156b8ff9-dcc4-42ce-b172-4fb0855c04d2.png)

**Comment by kevinrobert3** [comment]
Hello. When will this be added in

**Comment by VladislavFitz** [comment]
Hi @kevinrobert3. The feature is implemented in [v0.4.1](https://github.com/algolia/algoliasearch-helper-flutter/releases/tag/algolia_helper_flutter-v0.4.0).
