### ISSUE TITLE
Algolia search for flutter web

### ISSUE THREAD

**Issue by hpomgithub** [algolia/algoliasearch-helper-flutter#67]
Hi
I need to build a search for an e commerce website using Algolia and the library is not compatible with flutter web! So can you suggest me any workaround or any time by which we can get the Algolia search for web?

**Comment by hpomgithub** [comment]
Hi @Haroenv , 
Thanks for replying! But I need it for flutter and InstantSearch is in JS. Is there any way out by which we can use it with flutter?

**Comment by VladislavFitz** [comment]
Hi @hpomgithub ,
Although web compatibility is not declared on pub.dev, the package should work with web applications. Try adding it as a dependency.

**Comment by hpomgithub** [comment]
okay, I will try.
Thank You.
