### ISSUE TITLE
Add support for "Around" queries

### ISSUE THREAD

**Issue by Wackymax** [algolia/algoliasearch-helper-flutter#72]
**Is your feature request related to a problem? Please describe 🙏**  
Currently when using the HitSearcher you can't define any of the "around" parameters for the index search.

**Describe the solution you'd like 🤔**  
Adding the parameters to the search state so that it is passed into the index search.

**Describe alternatives you've considered ✨**  
Currently I have to make use of the pure dart implementation since that exposes the properties.

**Additional context**  
None

**Comment by VladislavFitz** [comment]
Finally added in [v0.5.0](https://github.com/algolia/algoliasearch-helper-flutter/releases/tag/algolia_helper_flutter-v0.5.0). Thanks again for your contribution  @Wackymax !

**Comment by Wackymax** [comment]
Glad I could contribute 😊. Thank you!On 02 Oct 2023, at 18:17, Vladislav Fitc ***@***.***> wrote:﻿
Finally added in v0.5.0. Thanks again for your contribution  @Wackymax !
