### ISSUE TITLE
Recommendation features for flutter/dart

### ISSUE THREAD

**Issue by Surajshr** [algolia/algoliasearch-helper-flutter#74]
I am currently using Algolia in my flutter app for the search and Recommend feature. There are different package for searching features one is from Algolia itself and another package is provided by knoxpo.com which is good for the search feature. but there is no mention of how can I fetch Recommend models data in Algolia . I request Algolia team to add  recommend features for flutter and more support.

I have also use official API to fetch data from Recommend feature using different trained model. but somehow it providing me a slow response and also I don't think this is the appropriate thing to do.  It will be great if any one from the community can help me with this if there is any alternative.

**Comment by VladislavFitz** [comment]
Hi @Surajshr ,
Thank you for using Algolia in your Flutter app. We understand your need for integrating the Recommend feature more seamlessly. For this purpose, we provide the official Dart API client, which supports the Recommend features. You can find it [here](https://github.com/algolia/algoliasearch-client-dart/tree/2f13426013d4b011f5f85eb5d0ece886bc3813cc/packages/client_recommend).
