### ISSUE TITLE
Algolia Events triggered from Segment but not shown in algolia dashboard

### ISSUE THREAD

**Issue by Abisheik-IAN** [algolia/algoliasearch-helper-flutter#80]
I have used the algolia_helper_flutter: ^0.3.1 as the zip and integrated directly to the project, because the plugin is not merged properly so we don't have the click anayltics param.After integrating it directly i can trigger the event of segment using algolia params also.

Segment.track(eventName: 'test', options: {
      'product_id': '507f1f77bcf86cd799439011',
      'sku': 'G-32',
      'category': 'Games',
      'name': 'Monopoly: 3rd Edition',
      'brand': 'Hasbro',
      'variant': '200 pieces',
      'price': 18.99,
      'quantity': 1,
      'coupon': 'MAYDEALS',
      'position': 3,
      'url': 'https://www.example.com/product/path',
      'image_url': 'https://www.example.com/product/path.jpg',

//algolia params
      'index': 'my-algolia-index',
      'eventType': 'click',
      'queryID': _shoeSearcher.responses,
      'objectID': '131280270'
    });

Algolia Events triggered from Segment but not shown in algolia dashboard

I have used the algolia_helper_flutter: ^0.3.1 as the zip and integrated directly to the project, because the plugin is not merged properly so we don't have the click anayltics param.After integrating it directly i can trigger the event of segment using algolia params also.

Segment.track(eventName: 'test', options: {
      'product_id': '507f1f77bcf86cd799439011',
      'sku': 'G-32',
      'category': 'Games',
      'name': 'Monopoly: 3rd Edition',
      'brand': 'Hasbro',
      'variant': '200 pieces',
      'price': 18.99,
      'quantity': 1,
      'coupon': 'MAYDEALS',
      'position': 3,
      'url': 'https://www.example.com/product/path',
      'image_url': 'https://www.example.com/product/path.jpg',

//algolia params
      'index': 'my-algolia-index',
      'eventType': 'click',
      'queryID': _shoeSearcher.responses,
      'objectID': '131280270'
    });

In segment the event delivered successfully, but i cannot see any trace in the algolia dashboard.

<img width="1425" alt="Screenshot 2023-05-26 at 1 51 12 PM" src="https://github.com/algolia/algoliasearch-helper-flutter/assets/75483357/4542d753-6f59-4e38-b464-2453f54e3100">
<img width="1426" alt="Screenshot 2023-05-24 at 6 41 49 PM" src="https://github.com/algolia/algoliasearch-helper-flutter/assets/75483357/11b20baf-725b-48ca-af4d-3dcdb60938af">

Am expecting to visible the event in algolia.

**Comment by VladislavFitz** [comment]
Hi @Abisheik-IAN ,

Thank you for reporting this issue. 
Actually, there is an outdated version of `algolia_helper` in the  pubspec of the `algolia_helper_flutter` package. I'll release a patch to fix this. 
In the meantime you can explicitly add `algolia_helper` in the pubspec of your application to 0.3.1 and get the access to Insights features including the `clickAnalytics` flag. 

Regarding the issue with Segment, firstly, I'd like to clarify that the responsibility of sending events properly to Algolia lies with the Segment library.

However, I did notice something interesting while examining your code. It appears that a peculiar value (`_shoeSearcher.responses`) is being assigned to the queryID parameter. Please note that the queryID value you provide should match the [one received in the Algolia search response](https://github.com/algolia/algoliasearch-helper-flutter/blob/e29abf041cb0c62fdd52795c6ba1c30fe88f38b3/helper_dart/lib/src/search_response.dart#L31) which appears when you set `clickAnalytics` to true. It's possible that the value currently assigned is not correct, which may result in successful capture in the Segment dashboard but a rejection by the Algolia dashboard.

To resolve the issue, I recommend double-checking the queryID parameter in your code. Make sure it corresponds to the actual queryID received from Algolia. Correcting this value might enable successful transmission of events to the Algolia Dashboard.

If the issue persists even after verifying the queryID parameter, I would suggest reaching out to the support team or the documentation of the Segment library. They should be able to provide further guidance on how to ensure the successful transmission of events to the Algolia Dashboard.

Please let me know if you have any additional questions or need further assistance. I'm here to help!

**Comment by Abisheik-IAN** [comment]
Hi @VladislavFitz  thanks for the suggestion i will verify the query id and if we add the ⁠algolia_helper directly also it take the older versions only according to algolia_helper_flutter plugin's pubspec

**Comment by Abisheik-IAN** [comment]
Hi @VladislavFitz  Still facing same issue
<img width="1391" alt="Screenshot 2023-05-29 at 3 51 47 PM" src="https://github.com/algolia/algoliasearch-helper-flutter/assets/75483357/3fbd6f23-2255-481e-a7ae-1c46c9c7308e">
<img width="422" alt="Screenshot 2023-05-29 at 3 52 05 PM" src="https://github.com/algolia/algoliasearch-helper-flutter/assets/75483357/068498a0-b92e-49d7-b036-7dee9484382a">
